name: 'Release'

on:   
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `app-v${process.env.PACKAGE_VERSION}`,
              name: `Desktop App v${process.env.PACKAGE_VERSION}`,
              body: 'Take a look at the assets to download and install this app.',
              draft: true,
              prerelease: false
            })
            return data.id

  build-tauri:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libnfc-dev libpcsclite-dev

      - name: Install Choco (windows)
        if: matrix.platform == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: -h
      - name: Install dependencies (windows)
        if: matrix.platform == 'windows-latest'
        run: choco install cmake doxygen.install -y
      - name: Download libnfc (windows)
        if: matrix.platform == 'windows-latest'
        run: |
          curl -L https://github.com/nfc-tools/libnfc/releases/download/libnfc-1.8.0/libnfc-1.8.0.tar.bz2 -o libnfc.tar.bz2
      - name: Extract libnfc (windows)
        if: matrix.platform == 'windows-latest'
        uses: ihiroky/extract-action@v1
        with:
          file_path: libnfc.tar.bz2
          extract_dir: ${{ github.workspace }}
      - name: prepare compilation libusb & libnfc (windows)
        if: matrix.platform == 'windows-latest'
        run: |
          ls
          cd libnfc-1.8.0
          mkdir build
          cd build 
          curl -L https://sourceforge.net/projects/libusb-win32/files/libusb-win32-releases/1.2.6.0/libusb-win32-bin-1.2.6.0.zip -o libusb-win32.zip
          unzip libusb-win32.zip
          mv libusb-win32-bin-1.2.6.0 LibUSB-Win32
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .. && cmake --build .
          ls 
      - name: Add libnfc (ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          git clone https://github.com/nfc-tools/libnfc.git
          cd libnfc
          autoreconf -vis
          ./configure --with-drivers=all --sysconfdir=/etc --prefix=/usr
          make
          cp libnfc/.libs/libnfc.so ${{ github.workspace }}/src-tauri/lib/libnfc-x86_64-unknown-linux-gnu
      - name: install frontend dependencies
        run: |
          ls ${{github.workspace}}/src-tauri/lib
          yarn install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          client_id: ${{ secrets.CLIENT_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          back_url: "https://clikodrome.aldon.fr"
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    needs: [create-release, build-tauri]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
